import Home from "./pages/home/Home";
import Splash from "./pages/home/Splash";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Content from "./pages/landing page/Content";
import LandingOne from "./pages/output/LandingOne";
import LandingTwo from "./pages/output/LandingTwo";

function App() {
  return (
    <BrowserRouter>
      <div className="App">
        <Routes>
          <Route path="/" element={<Splash />} />
          <Route path="/home" element={<Home />} />
          <Route exact path="/landing" element={<Content />} />

{/* THESE ROUTES ARE ONLY FOR THE PRESENTATION AND THEIR CONTENT IS COMPLETELY GENERATED BY LANDGPT */}
          <Route path="/one" element={<LandingOne />} />
          <Route path="/two" element={<LandingTwo />} />
        </Routes>
      </div>
    </BrowserRouter>
  );
}

export default App;
